# Generated by Django 4.1.7 on 2023-02-16 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sempleapp', '0002_material_productmaterial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmaterial',
            name='material',
        ),
        migrations.RemoveField(
            model_name='productmaterial',
            name='product',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='ProductMaterial',
        ),
    ]
